export const Images = {
    ProfilePicture : require('../Assets/Images/ProfileImage.jpeg'),
    ProfilePictureLoading : require('../Assets/Images/ProfileImageLoading.jpg'),
    // ProfilePicture2 : require('../Assets/Images/ProfileImage2.jpeg'),
    SmileyEmoji : require('../Assets/Images/SmileyEmoji.png'),
    DeveloperImageHome : require('../Assets/Images/DeveloperImage.jpg'),
    DeveloperImageHomeLoading : require('../Assets/Images/DeveloperImageLoading.jpg'),
    PlatformTheme : require('../Assets/Images/Platforms.png'),
    PlatformThemeLoading : require('../Assets/Images/PlatformsLoading.png'),
    AppDeveloperTheme : require('../Assets/Images/AppDeveloperImage.png'),
    AppDeveloperThemeLoading : require('../Assets/Images/AppDeveloperImageLoading.png'),
    SmileyEmojiGoggles : require('../Assets/Images/SmileyEmojiGoggles.png'),
    TaralShowcase4 : require('../Assets/Images/TaralShowcase/Taral-4.png'),
    TaralShowcase5 : require('../Assets/Images/TaralShowcase/Taral-5.png'),
    TaralShowcase8 : require('../Assets/Images/TaralShowcase/Taral-8.png'),
    TaralShowcase9 : require('../Assets/Images/TaralShowcase/Taral-9.png'),
    TaralShowcase11 : require('../Assets/Images/TaralShowcase/Taral-11.png'),
    TaralShowcase12 : require('../Assets/Images/TaralShowcase/Taral-12.png'),
    TaralShowcase14 : require('../Assets/Images/TaralShowcase/Taral-14.png'),
    TaralShowcase15 : require('../Assets/Images/TaralShowcase/Taral-15.png'),
    CalorieTrackerShowcaseVideo : require('../Assets/Images/TrackCalShowcase/trackCalShowcase.mp4'),
    IntroductionCover : require('../Assets/Images/IntroductionCover.png'),
    IntroductionCoverLoading : require('../Assets/Images/IntroductionCoverLoading.png'),
    ServicesImage : require('../Assets/Images/ServicesImage.png'),
    ServicesImageLoading : require('../Assets/Images/ServicesImageLoading.png'),
    BackgroundImage:require('../Assets/Images/BackgroundImage.jpg'),
    BackgroundImageLoading:require('../Assets/Images/BackgroundImageLoading.jpg'),
    sNProjectSnapshot1 : require('../Assets/Images/SNDigitech/ProjectSnapshot1.png'),
    sNProjectSnapshot2 : require('../Assets/Images/SNDigitech/ProjectSnapshot2.png'),
    sNProjectSnapshot3 : require('../Assets/Images/SNDigitech/ProjectSnapshot3.png'),
    sNProjectSnapshot4 : require('../Assets/Images/SNDigitech/ProjectSnapshot4.png'),
    sNProjectSnapshot5 : require('../Assets/Images/SNDigitech/ProjectSnapshot5.png'),
    sNProjectSnapshot6 : require('../Assets/Images/SNDigitech/ProjectSnapshot6.png'),
    findLocationProjectSnapshot1 : require('../Assets/Images/FindLocation/ProjectSnapshot1.png'),
    findLocationProjectSnapshot2 : require('../Assets/Images/FindLocation/ProjectSnapshot2.png'),
    findLocationProjectSnapshot3 : require('../Assets/Images/FindLocation/ProjectSnapshot3.png'),
    findLocationProjectSnapshot4 : require('../Assets/Images/FindLocation/ProjectSnapshot4.png'),
    findLocationProjectSnapshot5 : require('../Assets/Images/FindLocation/ProjectSnapshot5.png'),
    findLocationProjectSnapshot6 : require('../Assets/Images/FindLocation/ProjectSnapshot6.png'),
    findLocationProjectSnapshot7 : require('../Assets/Images/FindLocation/ProjectSnapshot7.png'),
    findLocationProjectSnapshot8 : require('../Assets/Images/FindLocation/ProjectSnapshot8.png'),
    findLocationProjectSnapshot9 : require('../Assets/Images/FindLocation/ProjectSnapshot9.png'),
}