export const Images = {
    ProfilePicture : require('../Assets/Images/ProfileImage.jpeg'),
    ProfilePicture2 : require('../Assets/Images/ProfileImage2.jpeg'),
    SmileyEmoji : require('../Assets/Images/SmileyEmoji.png'),
    DeveloperImageHome : require('../Assets/Images/DeveloperImage.jpg'),
    PlatformTheme : require('../Assets/Images/Platforms.png'),
    AppDeveloperTheme : require('../Assets/Images/AppDeveloperImage.png'),
    SmileyEmojiGoggles : require('../Assets/Images/SmileyEmojiGoggles.png'),
    // TaralShowcase1 : require('../Assets/Images/TaralShowcase/Taral-1.jpg'),
    TaralShowcase2 : require('../Assets/Images/TaralShowcase/Taral-2.jpg'),
    TaralShowcase3 : require('../Assets/Images/TaralShowcase/Taral-3.jpg'),
    TaralShowcase4 : require('../Assets/Images/TaralShowcase/Taral-4.jpg'),
    TaralShowcase5 : require('../Assets/Images/TaralShowcase/Taral-5.jpg'),
    TaralShowcase6 : require('../Assets/Images/TaralShowcase/Taral-6.jpg'),
    TaralShowcase7 : require('../Assets/Images/TaralShowcase/Taral-7.jpg'),
    TaralShowcase8 : require('../Assets/Images/TaralShowcase/Taral-8.jpg'),
    TaralShowcase9 : require('../Assets/Images/TaralShowcase/Taral-9.jpg'),
    TaralShowcase10 : require('../Assets/Images/TaralShowcase/Taral-10.jpg'),
    TaralShowcase11 : require('../Assets/Images/TaralShowcase/Taral-11.jpg'),
    TaralShowcase12 : require('../Assets/Images/TaralShowcase/Taral-12.jpg'),
    TaralShowcase13 : require('../Assets/Images/TaralShowcase/Taral-13.jpg'),
    TaralShowcase14 : require('../Assets/Images/TaralShowcase/Taral-14.jpg'),
    TaralShowcase15 : require('../Assets/Images/TaralShowcase/Taral-15.jpg'),
    TaralShowcase16 : require('../Assets/Images/TaralShowcase/Taral-16.mp4'),
    TaralShowcase17 : require('../Assets/Images/TaralShowcase/Taral-17.mp4'),
    CoverPhoto : require('../Assets/Images/ReactBackgroundImage.jpg'),
    CalorieTrackerShowcaseVideo : require('../Assets/Images/TrackCalShowcase/trackCalShowcase.mp4'),
    MesaImage1 : require('../Assets/Images/Mesa/Mesa1.jpg'),
    MesaImage2 : require('../Assets/Images/Mesa/Mesa2.jpg'),
    MesaImage3 : require('../Assets/Images/Mesa/Mesa3.JPG'),
    MesaImage4 : require('../Assets/Images/Mesa/Mesa4.jpg'),
    MesaImage5 : require('../Assets/Images/Mesa/Mesa5.png'),
    NSSImage1 : require('../Assets/Images/NSS_Pics/NSS1.JPG'),
    NSSImage2 : require('../Assets/Images/NSS_Pics/NSS2.jpg'),
    NSSImage3 : require('../Assets/Images/NSS_Pics/NSS3.jpg'),
    NSSImage4 : require('../Assets/Images/NSS_Pics/NSS4.jpg'),
    NSSImage5 : require('../Assets/Images/NSS_Pics/NSS5.jpg'),
    NSSImage6 : require('../Assets/Images/NSS_Pics/NSS6.jpg'),
    NSSImage7 : require('../Assets/Images/NSS_Pics/NSS7.jpg'),
    NSSImage8 : require('../Assets/Images/NSS_Pics/NSS8.jpg'),
    NSSImage9 : require('../Assets/Images/NSS_Pics/NSS9.jpg'),
    MPulseImage1 : require('../Assets/Images/Mpulse/Mpulse1.jpg'),
    MPulseImage2 : require('../Assets/Images/Mpulse/Mpulse2.jpg'),
    MPulseImage3 : require('../Assets/Images/Mpulse/Mpulse3.jpg'),
    MPulseImage4 : require('../Assets/Images/Mpulse/Mpulse4.jpg'),
    MPulseImage6 : require('../Assets/Images/Mpulse/Mpulse6.jpg'),
    MPulseImage7 : require('../Assets/Images/Mpulse/Mpulse7.jpg'),
    MPulseImage8 : require('../Assets/Images/Mpulse/Mpulse8.jpg'),
    MPulseImage9 : require('../Assets/Images/Mpulse/Mpulse9.jpg'),
    MPulseImage11 : require('../Assets/Images/Mpulse/Mpulse11.jpg'),
    MPulseImage12 : require('../Assets/Images/Mpulse/Mpulse12.jpg'),
    DeveloperCoverPhoto : require('../Assets/Images/developer_background.jpg'),
    PortfolioCoverPhoto : require('../Assets/Images/portfolio_cover_photo.jpg'),
    IntroductionCover : require('../Assets/Images/IntroductionCover.png'),
    ServicesImage : require('../Assets/Images/ServicesImage.png'),
    ExtraCurricular:require('../Assets/Images/ExtraCurricular.png'),
    BackgroundImage:require('../Assets/Images/BackgroundImage.jpg'),
}